// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eZeroOne.MailService.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class CustomerInvoice : CustomerInvoiceBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n<!doctype html>\r\n<html>\r\n\t<head>\r\n\t\t<meta charset=\"utf-8\">\r\n\t\t<title>Invoice</t" +
                    "itle>\r\n\t\t<style type=\"text/css\">\r\n        *\r\n{\r\n\tborder: 0;\r\n\tbox-sizing: conten" +
                    "t-box;\r\n\tcolor: inherit;\r\n\tfont-family: inherit;\r\n\tfont-size: inherit;\r\n\tfont-st" +
                    "yle: inherit;\r\n\tfont-weight: inherit;\r\n\tline-height: inherit;\r\n\tlist-style: none" +
                    ";\r\n\tmargin: 0;\r\n\tpadding: 0;\r\n\ttext-decoration: none;\r\n\tvertical-align: top;\r\n}\r" +
                    "\n\r\n/* heading */\r\n\r\nh1 { font: bold 100% sans-serif; letter-spacing: 0.5em; text" +
                    "-align: center; text-transform: uppercase; }\r\n\r\n/* table */\r\n\r\ntable { font-size" +
                    ": 75%; table-layout: fixed; width: 100%; }\r\ntable { border-collapse: separate; b" +
                    "order-spacing: 2px; }\r\nth, td { border-width: 1px; padding: 0.5em; position: rel" +
                    "ative; text-align: left; }\r\nth, td { border-radius: 0.25em; border-style: solid;" +
                    " }\r\nth { background: #EEE; border-color: #BBB; }\r\ntd { border-color: #DDD; }\r\n\r\n" +
                    "/* page */\r\n\r\nhtml { font: 16px/1 \'Open Sans\', sans-serif; overflow: auto; paddi" +
                    "ng: 0.5in; }\r\nhtml { background: #999; cursor: default; }\r\n\r\nbody { box-sizing: " +
                    "border-box; margin: 0 auto; overflow: hidden; padding: 0.5in; width: 8.5in; }\r\nb" +
                    "ody { background: #FFF; border-radius: 1px; box-shadow: 0 0 1in -0.25in rgba(0, " +
                    "0, 0, 0.5); }\r\n\r\n/* header */\r\n\r\nheader { margin: 0 0 3em; }\r\nheader:after { cle" +
                    "ar: both; content: \"\"; display: table; }\r\n\r\nheader h1 { background: #000; border" +
                    "-radius: 0.25em; color: #FFF; margin: 0 0 1em; padding: 0.5em 0; }\r\nheader addre" +
                    "ss { float: left; font-size: 75%; font-style: normal; line-height: 1.25; margin:" +
                    " 0 1em 1em 0; }\r\nheader address p { margin: 0 0 0.25em; }\r\nheader span, header i" +
                    "mg { display: block; float: right; }\r\nheader span { margin: 0 0 1em 1em; max-hei" +
                    "ght: 25%; max-width: 60%; position: relative; }\r\nheader img { max-height: 100%; " +
                    "max-width: 100%; }\r\nheader input { cursor: pointer; -ms-filter:\"progid:DXImageTr" +
                    "ansform.Microsoft.Alpha(Opacity=0)\"; height: 100%; left: 0; opacity: 0; position" +
                    ": absolute; top: 0; width: 100%; }\r\n\r\n/* article */\r\n\r\narticle, article address," +
                    " table.meta, table.inventory { margin: 0 0 3em; }\r\narticle:after { clear: both; " +
                    "content: \"\"; display: table; }\r\narticle h1 { clip: rect(0 0 0 0); position: abso" +
                    "lute; }\r\n\r\narticle address { float: left; font-size: 125%; font-weight: bold; }\r" +
                    "\n\r\n/* table meta & balance */\r\n\r\ntable.meta, table.balance { float: right; width" +
                    ": 36%; }\r\ntable.meta:after, table.balance:after { clear: both; content: \"\"; disp" +
                    "lay: table; }\r\n\r\n/* table meta */\r\n\r\ntable.meta th { width: 40%; }\r\ntable.meta t" +
                    "d { width: 60%; }\r\n\r\n/* table items */\r\n\r\ntable.inventory { clear: both; width: " +
                    "100%; }\r\ntable.inventory th { font-weight: bold; text-align: center;  width: 10%" +
                    "; }\r\ntable.inventory th:nth-child(1) { width: auto; }\r\n\r\ntable.inventory td { te" +
                    "xt-align: right; }\r\ntable.inventory td:nth-child(1) { text-align: left; }\r\ntable" +
                    ".inventory td:nth-child(3), table.inventory td:nth-child(4) { text-align: center" +
                    "; }\r\n\r\n/* table balance */\r\n\r\ntable.balance th, table.balance td { width: 50%; }" +
                    "\r\ntable.balance td { text-align: right; }\r\n\r\n/* aside */\r\n\r\naside h1 { border: n" +
                    "one; border-width: 0 0 1px; margin: 0 0 1em; }\r\naside h1 { border-color: #999; b" +
                    "order-bottom-style: solid; }\r\n\r\n\r\n@media print {\r\n\t* { -webkit-print-color-adjus" +
                    "t: exact; }\r\n\thtml { background: none; padding: 0; }\r\n\tbody { box-shadow: none; " +
                    "margin: 0; }\r\n\tspan:empty { display: none; }\r\n}\r\n\r\n@page { margin: 0; }\r\n       " +
                    " </style>\r\n\r\n\t</head>\r\n\t<body>\r\n\t\t<header>\r\n\t\t\t<h1>Invoice</h1>\r\n\t\t\t<address >\r\n" +
                    "\t\t\t\t<p>");
            
            #line 118 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(Invoice.CustomerName); 
            
            #line default
            #line hidden
            this.Write("</p>\r\n\t\t\t\t<p>");
            
            #line 119 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(Invoice.Address); 
            
            #line default
            #line hidden
            this.Write("</p>\r\n\t\t\t\t<p>");
            
            #line 120 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(Invoice.Telephone); 
            
            #line default
            #line hidden
            this.Write("</p>\r\n\t\t\t</address>\r\n\t\t\t<span><img alt=\"\" src=\"data:image/jpg;base64,iVBORw0KGgoA" +
                    "AAANSUhEUgAAAOgAAAA9CAYAAACnWiXkAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJ\r\nbWFnZVJlYWR5cc" +
                    "llPAAAAyJpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdp\r\nbj0i77u/IiBpZD0i" +
                    "VzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6\r\neD0iYWRvYmU6bnM6bW" +
                    "V0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0\r\nNTY2MSwgMjAxMi8wMi8w" +
                    "Ni0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJo\r\ndHRwOi8vd3d3LnczLm9yZy" +
                    "8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlw\r\ndGlvbiByZGY6YWJvdXQ9IiIg" +
                    "eG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAv\r\nIiB4bWxuczp4bXBNTT0iaHR0cD" +
                    "ovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RS\r\nZWY9Imh0dHA6Ly9ucy5hZG9iZS5j" +
                    "b20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpD\r\ncmVhdG9yVG9vbD0iQWRvYmUgUGhvdG" +
                    "9zaG9wIENTNiAoV2luZG93cykiIHhtcE1NOkluc3RhbmNl\r\nSUQ9InhtcC5paWQ6NzdFQTlCREJDMzBC" +
                    "MTFFM0E5RTQ5MDk2MEExREExNDkiIHhtcE1NOkRvY3Vt\r\nZW50SUQ9InhtcC5kaWQ6NzdFQTlCRENDMz" +
                    "BCMTFFM0E5RTQ5MDk2MEExREExNDkiPiA8eG1wTU06\r\nRGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJ" +
                    "RD0ieG1wLmlpZDo3N0VBOUJEOUMzMEIxMUUzQTlF\r\nNDkwOTYwQTFEQTE0OSIgc3RSZWY6ZG9jdW1lbn" +
                    "RJRD0ieG1wLmRpZDo3N0VBOUJEQUMzMEIxMUUz\r\nQTlFNDkwOTYwQTFEQTE0OSIvPiA8L3JkZjpEZXNj" +
                    "cmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1w\r\nbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pu5zuO0AAA" +
                    "dDSURBVHja7F3dcds4EEYyeQ9vJu+hKohS\r\nQegKpFRgugJZFViuQHYFpiuwXIHoCkJXEObdD+pARySL" +
                    "O56OWPwQJEXp+2Y4joc0Aezut7v4Webd\r\nfr8XAAAcJ95DBAAAggIAAIICAAgKAAAICgAACAoAICgAAC" +
                    "AoAICgAACAoAAAgKAAAIICAOCFDzYP\r\nfZrOkurHN83tl+rKPdpOq+uz5t5jdZVQTyvE1XV5gvLV2c2v" +
                    "6so0f8PZ722bzrwVz8MTlAa30txb\r\neRL0kgSnIz0I2p6gqxOUr85ucoagnP3eHvNgkeICAAgKAAAICg" +
                    "AgKAAAICgAACAoAICgAAB44cMJ\r\njmlKV30zW25iF3R1hUj82Z/7Qr+/ij97czvLv1X9/nhwT/a9FH57" +
                    "zceApGFcah+2HOF4Yrp+H3z4\r\nNJ3V70mdl2/FcwGC/p+Ui+qak7HrIMmyEX82p12MYyuaN8cviDiy3Q" +
                    "dN21l1LTVEnVO/E8t+yL7f\r\nd0zWlMaigxzPlYUR39C7OBQ0nmwENnZNuopND1ak/cfOKrK2ckJjT3Ej" +
                    "MqYfZAyRxfPyuZ/VtbZ4\r\n3gaSZE/Mu1JNP57oShzb2hoI1NbRtSXnDck3dWjvJ/37WJ3/D7KX2MEuf9" +
                    "tZRdb0XAk6rRHT1yNu\r\nW5I0tiBLU5q7JbJ1FeV85bk1RLul4R2yTytPOW5b6LLLdHbb0nk8tCHp+xGT" +
                    "c+vg0Uwk9yWpTRTO\r\nGyJMiGiROkZfk8fnnFVB6fzOQM60ZR8ejiySPgTKstYVSb3eE2IOuvL0ml0Krq" +
                    "A5gPKC3NxUecmv\r\nnkZlwvNBWysDmfODlJYz2MsA89EQ5Lw2kNNFH0+ki93A5OQc4I7kXtRkOGcChrqf" +
                    "DUHQvsFFICm4\r\n7w1Gu6RolzKRVL63TWVDSUa4qxmhEP9dOV4wf3/R0O/b2hxX51xCkHPKjMlEzohkF0" +
                    "ofMclp6CqT\r\nhUEmvxd/auVmyypKrslZNeHzOaS4ESOAncbI1T25uHFniAK+6Yz0jBMyvFtqa9KwoDJn" +
                    "shBdJNzU\r\nok+TY2mVelk4O1MkSxm5mfSRMe8ceu6pk8uV0OwAVGRdMvLy0tXYIiiXGi2FeZ9zyaQiau" +
                    "XtziNy\r\nLjVGeEisSS1tUgXE8vdHQxuFhtxt5kfcnFE5O5v9vEvGadnoI2UIUgxkZ1Knf1EfpIy/0M/Y" +
                    "YkpR\r\naFLj6BwIOmMEapvf3wr9CujMg6CZ43wpP/hpk8pFgeW4YKK5CzkjJjLYfGpAzeUSjS6KAW1tV9" +
                    "PR\r\nJvC6RK8ELYXfiZCpx2DmTBpoiw1D0MRjHC8dplgz6lMc+P1zg3wKBx1ydmHrsJIO0vdeUM07pwe6" +
                    "\r\nOjqCZp4T+q0jITiFvTp6xpIx+tjR4eQBZJhQyquUHQ9oczLlvLck6dQwv7V1Rn1kDaHWQBJKeRPP\r\n" +
                    "IHOyKW4UwFvXnw9F0DZEmIl2Bxa6wprSXBM+GpxOW6d1LHaX0ly796h+iofl+15M8Entj21Dvokc\r\nc8" +
                    "epwymCO2PdC1Bu1i9B1QkoG3LK1FkuWMmtjtVAUTQ6Y93KqPlkIQO1mCR19FUELmT4cCJkcJ2z\r\nxYGj" +
                    "oi04b1xSxHpuUPKXjvqTUbsrjYzaHBi4GDE5Y8McWs7P5dZYflhadlB+BoJ6GHDEEHTXIUG5\r\nY3uSKF" +
                    "c9y7PeZqqRybXgP3L9YtBXOVKCLhhHyh2wOPsUN2eM34Uoru8PgW+MIZvIGXVITsG0Hxki\r\nSWlI58eK" +
                    "hJFb1qeuxkbQZyYlSS3fcePx/hCYtkipk8B9eWxwTJzzSzyi5MIyldzTvHxLzuCGieh9\r\nwUtXVLEyPW" +
                    "eCbgyLGibhrA3pbXZExlAnZx/R6MogNy4a6/qdWuhDPZtQSr0SA6+cttDVInSDYyNo\r\nyRiEqsxINPce" +
                    "hP6gvcSyh74Lpm86I3/qUbZ3jGFeW0bjOjiZXzPTDRnNi4HtTJdNpJroqZxLUIxx\r\nH1QdeI8YkrrUHy" +
                    "qD6Dp6vjARRaV09+LfcrVLy9Q2CTh3vhX66pQb0XzuuBR8TfCaIktOz5pqJ1U/\r\nhl7rSBmn8005Jjrq" +
                    "Z/OtouRcCKoOc3NFxlOHtFCS+XtP6Tm3t5h4KjEKLNulJqKrus+mTONe8KvU\r\nLmsEd2L4Lxg+GvqbCo" +
                    "+SODlHfSuenQrRx3pQwabKv8/32Bq/71ZKycy/Z4H7mTHp5bWGhC4VMKa2\r\nl0dgX7lwr2qySc+dj3WO" +
                    "+SSRFMKkRWoqFdD3pzU2HiTdUD/vGaWHXlDhSLI2ZDa+xwNXov+9YJMM\r\nXG1rVUVITgaX50TQelSaCL" +
                    "u6TLVSOxnQU2fC7khYTgavvmqQa8YXifCrhzljZInga0m/U78zS/0p\r\nfRzjf6R7ReMpLXQ6qcipxqDb" +
                    "rkvof6u3xrv9ft9qBKGPNgXAUF+W90FMfa2fhHqlfpbiNJDQOA/1\r\nUYpxfS2/ya7kwl/hOq/slaAAAH" +
                    "QHVLMAAAgKAAAICgAgKAAAICgAACAoAICgAACAoAAAggIAAIIC\r\nAACCAsBR428BBgB3F8VSXU+pMwAA" +
                    "AABJRU5ErkJggg==\"></span>\r\n\t\t</header>\r\n\t\t<article>\r\n\t\t\t<table class=\"meta\">\r\n\t\t" +
                    "\t\t<tr>\r\n\t\t\t\t\t<th><span>Invoice #</span></th>\r\n\t\t\t\t\t<td><span>");
            
            #line 176 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(Invoice.InvoiceId); 
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th><span>Date</span></th>\r\n\t\t\t\t\t<td><spa" +
                    "n>");
            
            #line 180 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(Invoice.InvoicedDate.ToString("MMMM, d yyyy")); 
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th><span>Amount Due</span></th>\r\n\t\t\t\t\t<t" +
                    "d><span>$</span><span>");
            
            #line 184 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(Invoice.BillAmount.ToString()); 
            
            #line default
            #line hidden
            this.Write(@"</span></td>
				</tr>
			</table>
			<table class=""inventory"">
				<thead>
					<tr>
						<th><span>Item</span></th>
						<th><span>Price</span></th>
						<th><span>Quantity</span></th>
						<th><span>Discount (%)</span></th>
						<th><span>Tax</span></th>
						<th><span>Total</span></th>
					</tr>
				</thead>
				<tbody>
					");
            
            #line 199 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 foreach (var item in Invoice.ItemDetails)
					{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td><span>");
            
            #line 202 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(item.ItemName); 
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t\t\t<td><span data-prefix>%</span><span>");
            
            #line 203 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(item.Price.ToString()); 
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t\t\t<td><span>");
            
            #line 204 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(item.Qty.ToString()); 
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t\t\t<td><span>");
            
            #line 205 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(item.Discount.ToString()); 
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t\t\t<td><span data-prefix>$</span><span>");
            
            #line 206 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(item.Tax.ToString()); 
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t\t\t<td><span data-prefix>$</span><span>");
            
            #line 207 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(item.Total.ToString()); 
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t");
            
            #line 209 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t</tbody>\r\n\t\t\t</table>\r\n\r\n\t\t\t<table class=\"balance\">\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th><span" +
                    " >Total</span></th>\r\n\t\t\t\t\t<td><span data-prefix>$</span><span>");
            
            #line 216 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(Invoice.TotalAmount.ToString()); 
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th><span >Total Discount</span></th>\r\n\t\t" +
                    "\t\t\t<td><span data-prefix>$</span><span >");
            
            #line 220 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(Invoice.TotalDiscount.ToString()); 
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th><span >Total Tax</span></th>\r\n\t\t\t\t\t<t" +
                    "d><span data-prefix>$</span><span>");
            
            #line 224 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(Invoice.TotalTax.ToString()); 
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th><span >Total Bill Amount</span></th>\r" +
                    "\n\t\t\t\t\t<td><span data-prefix>$</span><span>");
            
            #line 228 "E:\Personal Work\Archives\Repo\eHorakelle\he\eHorakelle\eZeroOne.MailService\Templates\CustomerInvoice.tt"
 WriteLine(Invoice.BillAmount.ToString()); 
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t</tr>\r\n\t\t\t</table>\r\n\t\t</article>\r\n\t\t<aside>\r\n\t\t\t<h1><span >Addi" +
                    "tional Notes</span></h1>\r\n\t\t\t<div >\r\n\t\t\t\t<p>A finance charge of 1.5% will be mad" +
                    "e on unpaid balances after 30 days.</p>\r\n\t\t\t</div>\r\n\t\t</aside>\r\n\t</body>\r\n</html" +
                    ">");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class CustomerInvoiceBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
